/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google */
        post: operations["google_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apple */
        post: operations["apple_auth_apple_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_users_me_profile_get"];
        /** Replace Profile */
        put: operations["replace_profile_users_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_users_me_profile_patch"];
        trace?: never;
    };
    "/users/me/targets/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Targets
         * @description The profile-setup screen shows targets as the user types. Nothing is stored.
         */
        post: operations["preview_targets_users_me_targets_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Targets */
        get: operations["read_targets_users_me_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Reminders */
        patch: operations["update_reminders_users_me_reminders_patch"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_users_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/body-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_body_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/body-logs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_body_logs_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/body-logs/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record */
        put: operations["record_body_logs__day__put"];
        post?: never;
        /** Remove */
        delete: operations["remove_body_logs__day__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Day */
        get: operations["read_day_days__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Day */
        patch: operations["update_day_days__day__patch"];
        trace?: never;
    };
    "/days/{day}/meals/{meal_time}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Eaten */
        patch: operations["mark_eaten_days__day__meals__meal_time__patch"];
        trace?: never;
    };
    "/days/{day}/workout/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Log Set */
        put: operations["log_set_days__day__workout_sets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{day}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Plan
         * @description Today's plate. Generates one on first look when auto-assign is on.
         */
        get: operations["read_plan_days__day__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{day}/plan/shuffle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shuffle Plan */
        post: operations["shuffle_plan_days__day__plan_shuffle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/days/{day}/plan/{meal_time}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Swap Plan Item
         * @description Swap one food on today's plate; the portion is converted for you.
         */
        patch: operations["swap_plan_item_days__day__plan__meal_time__items_patch"];
        trace?: never;
    };
    "/food-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_food_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Foods */
        get: operations["search_foods_foods_get"];
        put?: never;
        /** Add Food */
        post: operations["add_food_foods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foods/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Food */
        delete: operations["remove_food_foods__food_id__delete"];
        options?: never;
        head?: never;
        /** Edit Food */
        patch: operations["edit_food_foods__food_id__patch"];
        trace?: never;
    };
    "/foods/{food_id}/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exchanges
         * @description Same-category swaps. `grams` defaults to the food's usual portion, `match` to
         *     the category's own rule.
         */
        get: operations["list_exchanges_foods__food_id__exchanges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meals */
        get: operations["list_meals_meals_get"];
        put?: never;
        /** Create Meal */
        post: operations["create_meal_meals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate
         * @description Totals for a draft meal. Stores nothing — the edit screen calls this while typing.
         */
        post: operations["calculate_meals_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{meal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Meal */
        get: operations["read_meal_meals__meal_id__get"];
        put?: never;
        post?: never;
        /** Remove Meal */
        delete: operations["remove_meal_meals__meal_id__delete"];
        options?: never;
        head?: never;
        /** Update Meal */
        patch: operations["update_meal_meals__meal_id__patch"];
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_exercises_get"];
        put?: never;
        /** Add Exercise */
        post: operations["add_exercise_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Exercise */
        delete: operations["remove_exercise_exercises__exercise_id__delete"];
        options?: never;
        head?: never;
        /** Edit Exercise */
        patch: operations["edit_exercise_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/workout-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_workout_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_workout_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Template */
        get: operations["read_template_workout_templates__template_id__get"];
        /** Replace Template */
        put: operations["replace_template_workout_templates__template_id__put"];
        post?: never;
        /** Remove Template */
        delete: operations["remove_template_workout_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-templates/{template_id}/items/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Items */
        put: operations["reorder_items_workout_templates__template_id__items_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workout-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Schedule */
        get: operations["read_schedule_workout_schedule_get"];
        /** Set Schedule */
        put: operations["set_schedule_workout_schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Device */
        post: operations["register_device_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BodyLogIn */
        BodyLogIn: {
            /** Weight Kg */
            weight_kg?: number | null;
            /** Waist Cm */
            waist_cm?: number | null;
        };
        /** BodyLogOut */
        BodyLogOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg: number | null;
            /** Waist Cm */
            waist_cm: number | null;
        };
        /** BodySummaryOut */
        BodySummaryOut: {
            /** Week Avg Weight */
            week_avg_weight: number | null;
            /** Week Avg Delta */
            week_avg_delta: number | null;
            /** Latest Waist */
            latest_waist: number | null;
            /** Weight Series */
            weight_series: components["schemas"]["TrendPointOut"][];
            /** Waist Series */
            waist_series: components["schemas"]["TrendPointOut"][];
        };
        /** CalculateIn */
        CalculateIn: {
            /** Items */
            items: components["schemas"]["MealItemIn"][];
        };
        /** DayFlowOut */
        DayFlowOut: {
            /** Steps */
            steps: string[];
            /** Completed */
            completed: string[];
            /** Current */
            current: string;
            /** Eaten Kcal */
            eaten_kcal: number;
        };
        /** DayPatch */
        DayPatch: {
            /** Workout Time */
            workout_time?: ("am" | "pm") | null;
            /** Location */
            location?: ("home" | "gym") | null;
            /** Steps */
            steps?: number | null;
            /**
             * Workout Done
             * @default false
             */
            workout_done: boolean;
        };
        /** DayPlanOut */
        DayPlanOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Meals */
            meals: components["schemas"]["PlannedMealOut"][];
            nutrients: components["schemas"]["NutrientsOut"];
        };
        /** DeviceIn */
        DeviceIn: {
            /** Push Token */
            push_token: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "ios" | "android";
        };
        /** ExchangeOut */
        ExchangeOut: {
            food: components["schemas"]["FoodOut"];
            /** Grams */
            grams: number;
            nutrients: components["schemas"]["NutrientsOut"];
            delta: components["schemas"]["NutrientsOut"];
            /** Capped */
            capped: boolean;
        };
        /** ExerciseIn */
        ExerciseIn: {
            /** Category Id */
            category_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /** Id */
            id: string;
            /** Category Id */
            category_id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Is Builtin */
            is_builtin: boolean;
        };
        /** FoodCategoryOut */
        FoodCategoryOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Swap By */
            swap_by: string;
            /** Sort Order */
            sort_order: number;
        };
        /** FoodIn */
        FoodIn: {
            /** Category Id */
            category_id: string;
            /** Name */
            name: string;
            /**
             * State
             * @default na
             * @enum {string}
             */
            state: "raw" | "cooked" | "na";
            /** Kcal Per 100G */
            kcal_per_100g: number;
            /** Protein Per 100G */
            protein_per_100g: number;
            /** Fat Per 100G */
            fat_per_100g: number;
            /** Carb Per 100G */
            carb_per_100g: number;
            /**
             * Unit
             * @default g
             * @enum {string}
             */
            unit: "g" | "ml" | "piece" | "scoop" | "bowl";
            /** Grams Per Unit */
            grams_per_unit?: number | null;
            /** Usual Grams */
            usual_grams: number;
            /** Max Grams */
            max_grams: number;
        };
        /** FoodOut */
        FoodOut: {
            /** Id */
            id: string;
            /** Category Id */
            category_id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            per_100g: components["schemas"]["NutrientsOut"];
            /** Unit */
            unit: string;
            /** Grams Per Unit */
            grams_per_unit: number | null;
            /** Usual Grams */
            usual_grams: number;
            /** Max Grams */
            max_grams: number;
            /** Aliases */
            aliases: string[];
            /** Is Builtin */
            is_builtin: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemOrderIn */
        ItemOrderIn: {
            /** Item Ids */
            item_ids: string[];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MealIn */
        MealIn: {
            /** Name */
            name: string;
            /**
             * Tag
             * @default regular
             * @enum {string}
             */
            tag: "regular" | "light" | "occasional";
            /** Meal Times */
            meal_times: ("breakfast" | "lunch" | "dinner")[];
            /** Items */
            items: components["schemas"]["MealItemIn"][];
        };
        /** MealItemIn */
        MealItemIn: {
            /** Food Id */
            food_id: string;
            /** Grams */
            grams: number;
        };
        /** MealItemOut */
        MealItemOut: {
            /** Id */
            id: string;
            food: components["schemas"]["FoodOut"];
            /** Category Id */
            category_id: string;
            /** Grams */
            grams: number;
            nutrients: components["schemas"]["NutrientsOut"];
        };
        /** MealOut */
        MealOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tag */
            tag: string;
            /** Meal Times */
            meal_times: string[];
            /** Items */
            items: components["schemas"]["MealItemOut"][];
            nutrients: components["schemas"]["NutrientsOut"];
        };
        /** MealPatch */
        MealPatch: {
            /** Name */
            name?: string | null;
            /** Tag */
            tag?: ("regular" | "light" | "occasional") | null;
            /** Meal Times */
            meal_times?: ("breakfast" | "lunch" | "dinner")[] | null;
            /** Items */
            items?: components["schemas"]["MealItemIn"][] | null;
        };
        /**
         * MealTime
         * @enum {string}
         */
        MealTime: "breakfast" | "lunch" | "dinner" | "extras";
        /** NutrientsOut */
        NutrientsOut: {
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Carb G */
            carb_g: number;
        };
        /** PlannedMealOut */
        PlannedMealOut: {
            /** Meal Time */
            meal_time: string;
            /** Meal Id */
            meal_id: string | null;
            /** Name */
            name: string;
            /** Eaten */
            eaten: boolean;
            /** Items */
            items: components["schemas"]["MealItemOut"][];
            nutrients: components["schemas"]["NutrientsOut"];
        };
        /** ProfileIn */
        ProfileIn: {
            /**
             * Sex
             * @enum {string}
             */
            sex: "f" | "m";
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            /**
             * Activity Level
             * @enum {string}
             */
            activity_level: "sedentary" | "light" | "moderate" | "active";
            /**
             * Deficit Pct
             * @enum {integer}
             */
            deficit_pct: 10 | 12 | 15 | 20;
            /**
             * Auto Scale Carbs
             * @default true
             */
            auto_scale_carbs: boolean;
            /**
             * Auto Assign Meals
             * @default true
             */
            auto_assign_meals: boolean;
            /**
             * Workout Time
             * @default pm
             * @enum {string}
             */
            workout_time: "am" | "pm";
            /**
             * Default Location
             * @default home
             * @enum {string}
             */
            default_location: "home" | "gym";
            /** Reminder Time */
            reminder_time?: string | null;
            /**
             * Timezone
             * @default Australia/Brisbane
             */
            timezone: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Sex */
            sex: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Height Cm */
            height_cm: number;
            /** Weight Kg */
            weight_kg: number;
            /** Activity Level */
            activity_level: string;
            /** Deficit Pct */
            deficit_pct: number;
            /** Auto Scale Carbs */
            auto_scale_carbs: boolean;
            /** Auto Assign Meals */
            auto_assign_meals: boolean;
            /** Workout Time */
            workout_time: string;
            /** Default Location */
            default_location: string;
            /** Reminder Time */
            reminder_time: string | null;
            /** Timezone */
            timezone: string;
        };
        /** ProfilePatch */
        ProfilePatch: {
            /** Sex */
            sex?: ("f" | "m") | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Activity Level */
            activity_level?: ("sedentary" | "light" | "moderate" | "active") | null;
            /** Deficit Pct */
            deficit_pct?: (10 | 12 | 15 | 20) | null;
            /** Auto Scale Carbs */
            auto_scale_carbs?: boolean | null;
            /** Auto Assign Meals */
            auto_assign_meals?: boolean | null;
            /** Workout Time */
            workout_time?: ("am" | "pm") | null;
            /** Default Location */
            default_location?: ("home" | "gym") | null;
        };
        /** ProfileWithTargetsOut */
        ProfileWithTargetsOut: {
            profile: components["schemas"]["ProfileOut"];
            targets: components["schemas"]["TargetsOut"];
        };
        /** ProviderLoginIn */
        ProviderLoginIn: {
            /** Id Token */
            id_token: string;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Locale
             * @default zh-TW
             */
            locale: string;
        };
        /** RemindersPatch */
        RemindersPatch: {
            /** Reminder Time */
            reminder_time?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** ScheduleEntryIn */
        ScheduleEntryIn: {
            /** Weekday */
            weekday: number;
            /**
             * Location
             * @enum {string}
             */
            location: "home" | "gym";
            /** Template Id */
            template_id: string;
        };
        /** ScheduleEntryOut */
        ScheduleEntryOut: {
            /** Weekday */
            weekday: number;
            /** Location */
            location: string;
            /** Template Id */
            template_id: string;
        };
        /** SetLogIn */
        SetLogIn: {
            /** Template Item Id */
            template_item_id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Set Index */
            set_index: number;
            /** Reps Done */
            reps_done?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** ShuffleIn */
        ShuffleIn: {
            /** Meal Time */
            meal_time?: ("breakfast" | "lunch" | "dinner") | null;
        };
        /** SwapItemIn */
        SwapItemIn: {
            /** Item Id */
            item_id: string;
            /** To Food Id */
            to_food_id: string;
            /** Match */
            match?: ("carb" | "protein" | "kcal") | null;
        };
        /** TargetsOut */
        TargetsOut: {
            /** Bmr */
            bmr: number;
            /** Tdee */
            tdee: number;
            /** Kcal */
            kcal: number;
            /** Protein G */
            protein_g: number;
            /** Fat G */
            fat_g: number;
            /** Carb G */
            carb_g: number;
            /** Carb Scale */
            carb_scale: number;
        };
        /** TemplateIn */
        TemplateIn: {
            /** Category Id */
            category_id: string;
            /** Name */
            name: string;
            /**
             * Location
             * @enum {string}
             */
            location: "home" | "gym" | "both";
            /** Duration Min */
            duration_min?: number | null;
            /** Items */
            items?: components["schemas"]["TemplateItemIn"][];
        };
        /** TemplateItemIn */
        TemplateItemIn: {
            /** Id */
            id?: string | null;
            /** Exercise Id */
            exercise_id: string;
            /** Sets */
            sets?: number | null;
            /** Reps */
            reps: string;
            /** Weight Kg */
            weight_kg?: number | null;
            /**
             * Rest Sec
             * @default 60
             */
            rest_sec: number;
            /** Note */
            note?: string | null;
        };
        /** TemplateItemOut */
        TemplateItemOut: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Sort Order */
            sort_order: number;
            /** Sets */
            sets: number | null;
            /** Reps */
            reps: string;
            /** Weight Kg */
            weight_kg: number | null;
            /** Rest Sec */
            rest_sec: number;
            /** Note */
            note: string | null;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Id */
            id: string;
            /** Category Id */
            category_id: string;
            /** Name */
            name: string;
            /** Location */
            location: string;
            /** Duration Min */
            duration_min: number | null;
            /** Items */
            items: components["schemas"]["TemplateItemOut"][];
        };
        /** TodayOut */
        TodayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            flow: components["schemas"]["DayFlowOut"];
            targets: components["schemas"]["TargetsOut"];
            /** Streak */
            streak: number;
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** TrendPointOut */
        TrendPointOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
            /** Average 7D */
            average_7d: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apple_auth_apple_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWithTargetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_profile_users_me_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWithTargetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_users_me_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWithTargetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_targets_users_me_targets_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_targets_users_me_targets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_reminders_users_me_reminders_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemindersPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_users_me_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_body_logs_get: {
        parameters: {
            query?: {
                from_?: string | null;
                to?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_body_logs_summary_get: {
        parameters: {
            query?: {
                from_?: string | null;
                to?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodySummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_body_logs__day__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_body_logs__day__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_day_days__day__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_day_days__day__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_eaten_days__day__meals__meal_time__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
                meal_time: components["schemas"]["MealTime"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_set_days__day__workout_sets_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_plan_days__day__plan_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shuffle_plan_days__day__plan_shuffle_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShuffleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    swap_plan_item_days__day__plan__meal_time__items_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
                meal_time: components["schemas"]["MealTime"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwapItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_food_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodCategoryOut"][];
                };
            };
        };
    };
    search_foods_foods_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_food_foods_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_food_foods__food_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                food_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_food_foods__food_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                food_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exchanges_foods__food_id__exchanges_get: {
        parameters: {
            query?: {
                grams?: number | null;
                match?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                food_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meals_meals_get: {
        parameters: {
            query?: {
                meal_time?: string | null;
                q?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meal_meals_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_meals_calculate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutrientsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_meal_meals__meal_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_meal_meals__meal_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meal_meals__meal_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                meal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MealPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_exercises_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_exercise_exercises_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_exercise_exercises__exercise_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_exercise_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_workout_templates_get: {
        parameters: {
            query?: {
                location?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_workout_templates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_template_workout_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_template_workout_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_template_workout_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_items_workout_templates__template_id__items_order_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemOrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_schedule_workout_schedule_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_schedule_workout_schedule_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleEntryIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_devices_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
