// Lists the pictures in assets/exercise/ and the animations in assets/exercise-anim/ so the
// app can bundle them.
//
// Metro needs every `require('...webp')` written out in full, so a new file is only picked
// up after this runs. Run it whenever a file is added, renamed or removed:
//
//   npm run exercise-images
//
// A file's name, minus its extension, is the exercise id: `barbell-back-squat.png`. Add
// `-start` or `-end` for the two ends of a movement: `barbell-back-squat-start.png`.
// An animation is one looping file per exercise: `assets/exercise-anim/barbell-back-squat.webp`.
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Writes `src/workouts/figure/<output>.ts` mapping each file's id to its `require`. */
function list({ folder, output, name }) {
  const files = readdirSync(join(root, 'assets', folder))
    .filter((file) => /\.(png|webp|jpe?g)$/i.test(file))
    .sort();

  const entries = files
    .map((file) => `  '${file.replace(/\.[^.]+$/, '')}': require('../../../assets/${folder}/${file}'),`)
    .join('\n');

  writeFileSync(
    join(root, 'src', 'workouts', 'figure', `${output}.ts`),
    `// Generated by scripts/exercise-images.mjs. Do not edit; run \`npm run exercise-images\`.
export const ${name}: Record<string, number> = {
${entries}
};
`,
  );

  console.log(`${files.length} files listed in ${folder}.`);
}

list({ folder: 'exercise', output: 'exercise-images', name: 'EXERCISE_IMAGES' });
list({ folder: 'exercise-anim', output: 'exercise-animations', name: 'EXERCISE_ANIMATIONS' });
