// Lists the pictures in assets/exercise/ so the app can bundle them.
//
// Metro needs every `require('...png')` written out in full, so a new picture is only picked
// up after this runs. Run it whenever a file is added, renamed or removed:
//
//   npm run exercise-images
//
// A file's name, minus its extension, is the exercise id: `barbell-back-squat.png`. Add
// `-start` or `-end` for the two ends of a movement: `barbell-back-squat-start.png`.
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pictures = readdirSync(join(root, 'assets', 'exercise'))
  .filter((file) => /\.(png|webp|jpe?g)$/i.test(file))
  .sort();

const entries = pictures
  .map((file) => `  '${file.replace(/\.[^.]+$/, '')}': require('../../../assets/exercise/${file}'),`)
  .join('\n');

writeFileSync(
  join(root, 'src', 'workouts', 'figure', 'exercise-images.ts'),
  `// Generated by scripts/exercise-images.mjs. Do not edit; run \`npm run exercise-images\`.
export const EXERCISE_IMAGES: Record<string, number> = {
${entries}
};
`,
);

console.log(`${pictures.length} exercise pictures listed.`);
