"""Seed the translated built-in exercise catalog.

Rows are stable slugs. Re-running the seed updates only rows that are still built-ins,
so a user-owned row can never be overwritten by a future catalog revision.
"""

import asyncio
import sys

from app.db import get_conn

# slug, category, body region, equipment, zh-TW name, English name, zh-TW description,
# English description, location, MET (metabolic equivalent, only ever a shown estimate)
EXERCISES: tuple[tuple[str, str, str, str | None, str, str, str, str, str, float], ...] = (
    # Lower body
    (
        "barbell-back-squat",
        "strength",
        "lower_body",
        "barbell",
        "槓鈴深蹲",
        "Barbell Back Squat",
        "槓鈴置於上背，髖部向後下坐，保持軀幹穩定後站起。",
        "Brace the torso, sit the hips back and down, then stand through the feet.",
        "gym",
        5.0,
    ),
    (
        "barbell-romanian-deadlift",
        "strength",
        "lower_body",
        "barbell",
        "槓鈴羅馬尼亞硬舉",
        "Barbell Romanian Deadlift",
        "膝蓋微彎、髖部後推，沿腿放下槓鈴並以臀腿後側拉回。",
        "Hinge at the hips with soft knees and drive through the hamstrings to stand.",
        "gym",
        5.0,
    ),
    (
        "barbell-hip-thrust",
        "strength",
        "lower_body",
        "barbell",
        "槓鈴臀推",
        "Barbell Hip Thrust",
        "上背靠椅，向上推髖並在頂端收緊臀部。",
        "Rest the upper back on a bench, extend the hips and squeeze the glutes at the top.",
        "gym",
        5.0,
    ),
    (
        "dumbbell-goblet-squat",
        "strength",
        "lower_body",
        "dumbbell",
        "啞鈴高腳杯深蹲",
        "Dumbbell Goblet Squat",
        "雙手於胸前持啞鈴，控制下蹲並以全腳掌站起。",
        "Hold one dumbbell at the chest, squat under control and stand through the whole foot.",
        "both",
        4.5,
    ),
    (
        "dumbbell-reverse-lunge",
        "strength",
        "lower_body",
        "dumbbell",
        "啞鈴後撤弓箭步",
        "Dumbbell Reverse Lunge",
        "單腳向後跨步下沉，前腳穩定發力回到站姿。",
        "Step back into a lunge, then press through the front foot to return to standing.",
        "both",
        4.5,
    ),
    (
        "dumbbell-bulgarian-split-squat",
        "strength",
        "lower_body",
        "dumbbell",
        "啞鈴保加利亞分腿蹲",
        "Dumbbell Bulgarian Split Squat",
        "後腳置於椅上，前腿控制下沉並推回站姿。",
        "Elevate the rear foot, lower with control and drive through the front leg.",
        "both",
        4.5,
    ),
    (
        "leg-press-machine",
        "strength",
        "lower_body",
        "machine",
        "腿推機",
        "Leg Press",
        "雙腳穩踩踏板，控制下放至舒適深度後推回。",
        "Place both feet firmly on the platform, lower with control and press back up.",
        "gym",
        3.5,
    ),
    (
        "leg-extension-machine",
        "strength",
        "lower_body",
        "machine",
        "腿屈伸機",
        "Leg Extension",
        "固定大腿，伸直膝蓋時收緊股四頭肌，慢慢回放。",
        "Keep the thighs fixed, extend the knees and lower the weight slowly.",
        "gym",
        3.5,
    ),
    (
        "seated-leg-curl-machine",
        "strength",
        "lower_body",
        "machine",
        "坐姿腿彎舉機",
        "Seated Leg Curl",
        "固定骨盆，彎曲膝蓋帶動滾墊，控制回到起始位置。",
        "Anchor the hips, curl the pad with the hamstrings and return slowly.",
        "gym",
        3.5,
    ),
    (
        "standing-calf-raise-machine",
        "strength",
        "lower_body",
        "machine",
        "站姿提踵機",
        "Standing Calf Raise",
        "以前腳掌推起腳跟，在頂端停頓後緩慢下降。",
        "Press through the balls of the feet, pause at the top and lower the heels slowly.",
        "gym",
        3.5,
    ),
    (
        "bodyweight-squat",
        "strength",
        "lower_body",
        "bodyweight",
        "徒手深蹲",
        "Bodyweight Squat",
        "以舒適深度進行慢速深蹲，作為下肢暖身。",
        "Use slow, comfortable-depth squats to warm up the lower body.",
        "home",
        3.8,
    ),
    (
        "bodyweight-walking-lunge",
        "strength",
        "lower_body",
        "bodyweight",
        "徒手行走弓箭步",
        "Bodyweight Walking Lunge",
        "向前跨一步下蹲到後膝接近地面，起身時直接換腳前進。",
        "Step forward and lower until the rear knee nearly touches the floor, then alternate.",
        "home",
        4.0,
    ),
    (
        "glute-bridge",
        "strength",
        "lower_body",
        "bodyweight",
        "臀橋",
        "Glute Bridge",
        "仰躺屈膝，推髖至身體成一直線並收緊臀部。",
        "Lie on the back with bent knees, extend the hips and squeeze the glutes.",
        "home",
        3.5,
    ),
    # Upper body
    (
        "barbell-bench-press",
        "strength",
        "upper_body",
        "barbell",
        "槓鈴臥推",
        "Barbell Bench Press",
        "肩胛後收下沉，將槓鈴控制下降至胸前後推起。",
        "Set the shoulder blades, lower the bar to the chest with control and press up.",
        "gym",
        5.0,
    ),
    (
        "barbell-overhead-press",
        "strength",
        "upper_body",
        "barbell",
        "槓鈴肩推",
        "Barbell Overhead Press",
        "收緊核心，將槓鈴由肩前直線推至頭頂。",
        "Brace the core and press the bar in a straight line from the shoulders overhead.",
        "gym",
        5.0,
    ),
    (
        "barbell-bent-over-row",
        "strength",
        "upper_body",
        "barbell",
        "槓鈴俯身划船",
        "Barbell Bent-over Row",
        "維持髖關節折疊，將槓鈴拉向下腹並控制放下。",
        "Hold a hip hinge, row the bar toward the lower abdomen and lower with control.",
        "gym",
        5.0,
    ),
    (
        "dumbbell-incline-press",
        "strength",
        "upper_body",
        "dumbbell",
        "啞鈴上斜臥推",
        "Dumbbell Incline Press",
        "坐於上斜椅，將啞鈴從胸前穩定推至上方。",
        "On an incline bench, press the dumbbells from chest height to overhead.",
        "both",
        4.5,
    ),
    (
        "dumbbell-shoulder-press",
        "strength",
        "upper_body",
        "dumbbell",
        "啞鈴肩推",
        "Dumbbell Shoulder Press",
        "保持肋骨收下，將啞鈴自肩膀推至頭頂。",
        "Keep the ribs down and press the dumbbells from the shoulders overhead.",
        "both",
        4.5,
    ),
    (
        "dumbbell-one-arm-row",
        "strength",
        "upper_body",
        "dumbbell",
        "單手啞鈴划船",
        "One-arm Dumbbell Row",
        "以另一手支撐，將啞鈴拉向髖部，避免軀幹旋轉。",
        "Support the torso, row the dumbbell toward the hip and avoid rotating the trunk.",
        "both",
        4.5,
    ),
    (
        "dumbbell-lateral-raise",
        "strength",
        "upper_body",
        "dumbbell",
        "啞鈴側平舉",
        "Dumbbell Lateral Raise",
        "手肘微彎，將啞鈴舉至肩高並緩慢放下。",
        "With soft elbows, raise the dumbbells to shoulder height and lower slowly.",
        "both",
        3.5,
    ),
    (
        "lat-pulldown-machine",
        "strength",
        "upper_body",
        "machine",
        "下拉機",
        "Lat Pulldown",
        "胸口微抬，將把手拉向上胸，避免聳肩。",
        "Lift the chest slightly, pull the bar to the upper chest and keep the shoulders down.",
        "gym",
        3.5,
    ),
    (
        "seated-cable-row",
        "strength",
        "upper_body",
        "cable",
        "坐姿滑輪划船",
        "Seated Cable Row",
        "軀幹穩定，將把手拉向腹部並夾緊肩胛。",
        "Keep the torso steady, row the handle to the abdomen and squeeze the shoulder blades.",
        "gym",
        3.5,
    ),
    (
        "chest-press-machine",
        "strength",
        "upper_body",
        "machine",
        "胸推機",
        "Chest Press",
        "調整座椅使把手與胸口同高，穩定推出再控制回放。",
        "Set the seat so the handles meet the chest, press steadily and return with control.",
        "gym",
        3.5,
    ),
    (
        "push-up",
        "strength",
        "upper_body",
        "bodyweight",
        "伏地挺身",
        "Push-Up",
        "雙手略寬於肩，身體從頭到腳跟成一直線，下降到胸口接近地面再推起。",
        "Hands just wider than the shoulders, body in one line, lower the chest to the floor and press back up.",
        "home",
        4.0,
    ),
    (
        "pull-up",
        "strength",
        "upper_body",
        "bodyweight",
        "引體向上",
        "Pull-Up",
        "正握單槓略寬於肩，先收緊肩胛再把胸口拉向槓。",
        "Grip the bar just wider than the shoulders, set the shoulder blades, then pull the chest toward the bar.",
        "home",
        5.0,
    ),
    (
        "dip",
        "strength",
        "upper_body",
        "bodyweight",
        "雙槓撐體",
        "Parallel Bar Dip",
        "雙槓上撐起身體，屈肘下降到肩略低於肘的位置再撐回。",
        "Support on the bars, lower until the shoulders sit just below the elbows, then press back up.",
        "home",
        5.0,
    ),
    (
        "inverted-row",
        "strength",
        "upper_body",
        "bodyweight",
        "反向划船",
        "Inverted Row",
        "身體懸在低槓下方保持一直線，把胸口拉向槓再控制放下。",
        "Hang under a low bar with the body in one line and pull the chest to the bar.",
        "home",
        4.0,
    ),
    # Mobility
    (
        "cat-cow",
        "mobility",
        "mobility",
        "bodyweight",
        "貓牛式",
        "Cat-Cow",
        "四足跪姿交替拱背與伸展脊椎，配合平穩呼吸。",
        "On hands and knees, alternate spinal flexion and extension with steady breathing.",
        "home",
        2.3,
    ),
    (
        "worlds-greatest-stretch",
        "mobility",
        "full_body",
        "bodyweight",
        "世界上最偉大的伸展",
        "World's Greatest Stretch",
        "弓箭步加入胸椎旋轉，暖開髖部、腿後側與上背。",
        "Combine a lunge and thoracic rotation to warm the hips, hamstrings and upper back.",
        "home",
        2.8,
    ),
    (
        "hip-flexor-stretch",
        "mobility",
        "lower_body",
        "bodyweight",
        "髖屈肌伸展",
        "Hip Flexor Stretch",
        "半跪姿收緊臀部，骨盆微微後傾後向前移動。",
        "In a half-kneeling position, squeeze the glute and gently shift forward.",
        "home",
        2.3,
    ),
    (
        "thoracic-rotation",
        "mobility",
        "upper_body",
        "bodyweight",
        "胸椎旋轉",
        "Thoracic Rotation",
        "四足跪姿將手放在後腦，打開手肘旋轉上背。",
        "On hands and knees with a hand behind the head, rotate the upper back open.",
        "home",
        2.3,
    ),
    (
        "band-pull-apart",
        "mobility",
        "upper_body",
        "resistance_band",
        "彈力帶拉開",
        "Band Pull-apart",
        "手臂向前伸直，將彈力帶拉開並保持肩膀下沉。",
        "Hold the arms forward, pull the band apart and keep the shoulders down.",
        "home",
        2.8,
    ),
    (
        "shoulder-circles",
        "mobility",
        "upper_body",
        "bodyweight",
        "肩關節繞圈",
        "Shoulder Circles",
        "以可控制的大範圍向前後畫圈，讓肩關節暖開。",
        "Make controlled large circles forward and backward to warm the shoulders.",
        "home",
        2.3,
    ),
    # Cardio
    (
        "incline-treadmill-walk",
        "cardio",
        "lower_body",
        "treadmill",
        "上坡跑步機快走",
        "Incline Treadmill Walk",
        "設定可維持交談的速度與坡度，保持直立步行。",
        "Set a conversational pace and incline, then walk tall with a steady stride.",
        "gym",
        6.0,
    ),
    (
        "cycling-stationary",
        "cardio",
        "lower_body",
        "machine",
        "飛輪車",
        "Stationary Bike",
        "調整阻力到能維持節奏又略喘的程度，保持穩定踩踏。",
        "Set a resistance you can hold a rhythm against and pedal at a steady cadence.",
        "gym",
        6.8,
    ),
    (
        "rowing-erg",
        "cardio",
        "full_body",
        "machine",
        "划船機",
        "Rowing Machine",
        "腿推、body 後擺、手拉，回程反過來，節奏不要趕。",
        "Drive with the legs, swing the body, then pull; reverse the order coming back.",
        "gym",
        7.0,
    ),
    (
        "elliptical",
        "cardio",
        "full_body",
        "machine",
        "橢圓機",
        "Elliptical Trainer",
        "手腳同時出力，身體保持直立不要壓在把手上。",
        "Push with the arms as well as the legs and stay upright instead of leaning on the handles.",
        "gym",
        5.0,
    ),
    (
        "stair-climber",
        "cardio",
        "lower_body",
        "machine",
        "登階機",
        "Stair Climber",
        "整隻腳踩滿踏板，身體直立，不要把重量掛在扶手上。",
        "Plant the whole foot each step, stand tall, and keep your weight off the rails.",
        "gym",
        9.0,
    ),
    (
        "jump-rope",
        "cardio",
        "full_body",
        None,
        "跳繩",
        "Jump Rope",
        "用手腕帶繩，跳的高度只要夠繩子過去就好。",
        "Turn the rope from the wrists and jump only as high as the rope needs.",
        "home",
        11.0,
    ),
    (
        "running-outdoor",
        "cardio",
        "lower_body",
        None,
        "戶外跑步",
        "Outdoor Running",
        "用能講短句的配速起跑，落地在身體正下方。",
        "Start at a pace where you can still speak in short sentences, landing under your hips.",
        "outdoor",
        9.0,
    ),
    (
        "cycling-outdoor",
        "cardio",
        "lower_body",
        None,
        "戶外騎車",
        "Outdoor Cycling",
        "選一個能維持迴轉數的檔位，上坡提前換檔。",
        "Pick a gear you can keep spinning and shift before the hill, not on it.",
        "outdoor",
        7.5,
    ),
    (
        "swimming-freestyle",
        "cardio",
        "full_body",
        None,
        "自由式游泳",
        "Freestyle Swimming",
        "側轉換氣不要抬頭，打水從髖部出力。",
        "Breathe by rotating rather than lifting the head, and kick from the hips.",
        "outdoor",
        5.8,
    ),
    (
        "tennis-singles",
        "cardio",
        "full_body",
        None,
        "網球單打",
        "Tennis (Singles)",
        "維持分腿墊步，每球之間回到中線。",
        "Keep a split step going and recover to the middle between shots.",
        "outdoor",
        7.3,
    ),
    (
        "badminton",
        "cardio",
        "full_body",
        None,
        "羽球",
        "Badminton",
        "重心放低，擊球後回到中場等下一球。",
        "Stay low and return to the centre of the court after every shot.",
        "outdoor",
        5.5,
    ),
    (
        "basketball",
        "cardio",
        "full_body",
        None,
        "籃球",
        "Basketball",
        "把跑動當成訓練的一部分，不要只站在定點投籃。",
        "Treat the running as the workout rather than standing at one spot shooting.",
        "outdoor",
        6.5,
    ),
)


def _translation_rows() -> list[tuple[str, str, str]]:
    rows = []
    for slug, _, _, _, zh_name, en_name, zh_description, en_description, *_ in EXERCISES:
        rows.extend(
            (
                (f"exercise.{slug}.name", "zh-TW", zh_name),
                (f"exercise.{slug}.name", "en", en_name),
                (f"exercise.{slug}.description", "zh-TW", zh_description),
                (f"exercise.{slug}.description", "en", en_description),
            )
        )
    return rows


async def seed() -> int:
    async with get_conn() as conn:
        await conn.executemany(
            """
            INSERT INTO exercises (
                id, user_id, category_id, name_key, description_key, body_region, equipment,
                location, met
            ) VALUES (?, NULL, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (id) DO UPDATE SET
                category_id = excluded.category_id,
                name_key = excluded.name_key,
                description_key = excluded.description_key,
                body_region = excluded.body_region,
                equipment = excluded.equipment,
                location = excluded.location,
                met = excluded.met
            WHERE exercises.user_id IS NULL
            """,
            [
                (
                    slug,
                    category_id,
                    f"exercise.{slug}.name",
                    f"exercise.{slug}.description",
                    body_region,
                    equipment,
                    location,
                    met,
                )
                for slug, category_id, body_region, equipment, *_, location, met in EXERCISES
            ],
        )
        await conn.executemany(
            """
            INSERT INTO translations (key, locale, text) VALUES (?, ?, ?)
            ON CONFLICT (key, locale) DO UPDATE SET text = excluded.text
            """,
            _translation_rows(),
        )
    return len(EXERCISES)


if __name__ == "__main__":
    count = asyncio.run(seed())
    print(f"seeded {count} exercises", file=sys.stderr)
